apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotions
  labels:
    app: promotions
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: promotions
  template:
    metadata:
      labels:
        app: promotions
    spec:
      restartPolicy: Always
      containers:
        - name: promotions
          image: cluster-registry:5000/promotions:latest
          #image: promotions
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: RETRY_COUNT
              value: "10"
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: database-uri
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 30
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              cpu: "0.50"
              memory: "128Mi"
            requests:
              cpu: "0.25"
              memory: "64Mi"